const products = [
    {
      id: 1,
      category: 'Camisetas',
      name: 'Camiseta de entrenamiento',
      image: 'https://example.com/camiseta.jpg',
      price: 29.99,
      stock: 10,
      color: 'Rojo',
      size: 'M',
    },
    {
      id: 2,
      category: 'Pantalones',
      name: 'Pantalón deportivo',
      image: 'https://example.com/pantalon.jpg',
      price: 39.99,
      stock: 5,
      color: 'Negro',
      size: 'L',
    },
    {
      id: 3,
      category: 'Medias',
      name: 'Medias deportivas',
      image: 'https://example.com/medias.jpg',
      price: 9.99,
      stock: 15,
      color: 'Blanco',
      size: 'Única',
    },
    {
        id: 3,
        category: 'Ropa Deportiva',
        name: 'Medias deportivas',
        image: 'https://example.com/medias.jpg',
        price: 9.99,
        stock: 15,
        color: 'Blanco',
        size: 'Única',
      },
      {
        id: 4,
        category: 'Ropa Deportiva',
        name: 'Camiseta de running',
        image: 'https://example.com/camiseta_running.jpg',
        price: 24.99,
        stock: 8,
        color: 'Azul',
        size: 'S',
      },
      {
        id: 5,
        category: 'Ropa Deportiva',
        name: 'Short deportivo',
        image: 'https://example.com/short.jpg',
        price: 19.99,
        stock: 12,
        color: 'Negro',
        size: 'M',
      },
      {
        id: 6,
        category: 'Ropa Deportiva',
        name: 'Calcetines deportivos',
        image: 'https://example.com/calcetines.jpg',
        price: 6.99,
        stock: 20,
        color: 'Gris',
        size: 'Única',
      },
  ];

  export default products